export interface WitnessProperty {
  id?: string;
  title: string;
  address: string;
  area_built: number;
  price_asked: number;
  price_per_m2_asked: number;
  condition: string;
  has_parking: boolean;
  has_elevator: boolean;
  has_terrace: boolean;
  similarity_percentage: number;
  correction_factor: number;
  price_per_m2_adjusted: number;
  price_total_adjusted: number;
  notes: string;
}

export interface ValuationData {
  id?: string;
  client_name: string;
  client_phone?: string;
  client_email?: string;
  property_type: string;
  city: string;
  province: string;
  zone?: string;
  zipcode?: string;
  address?: string;
  cadastral_reference?: string;
  year_built?: number;
  area_built: number;
  area_useful?: number;
  rooms: number;
  bathrooms: number;
  condition: 'buen_estado' | 'a_reformar' | 'obra_nueva';
  energy_certificate: string;
  orientation: string;
  floor_height: string;
  purpose: 'venta' | 'alquiler' | 'herencia' | 'hipotecaria_orientativa';
  has_elevator: boolean;
  has_parking: boolean;
  has_terrace: boolean;
  has_pool: boolean;
  has_storage: boolean;
  has_heating: boolean;
  has_views: boolean;
  price_min: number;
  price_target: number;
  price_max: number;
  rent_target?: number;
  price_per_m2: number;
  gross_yield?: number;
  per_years?: number;
  ai_opinion?: string;
  agent_name?: string;
  comparable_properties?: WitnessProperty[];
  coefficients?: {
    state: number;
    elevator: number;
    parking: number;
    terrace: number;
    pool: number;
    storage: number;
    heating: number;
    energy: number;
    location_views: number;
    totalMultiplier: number;
  };
  created_at?: string;
}

export interface ValuationFormData {
  clientName: string;
  setClientName: (v: string) => void;
  clientPhone: string;
  setClientPhone: (v: string) => void;
  clientEmail: string;
  setClientEmail: (v: string) => void;
  purpose: 'venta' | 'alquiler' | 'herencia' | 'hipotecaria_orientativa';
  setPurpose: (v: 'venta' | 'alquiler' | 'herencia' | 'hipotecaria_orientativa') => void;
  address: string;
  setAddress: (v: string) => void;
  zone: string;
  setZone: (v: string) => void;
  city: string;
  setCity: (v: string) => void;
  province: string;
  setProvince: (v: string) => void;
  zipcode: string;
  setZipcode: (v: string) => void;
  cadastralReference: string;
  setCadastralReference: (v: string) => void;
  propertyType: string;
  setPropertyType: (v: string) => void;
  areaBuilt: number | '';
  setAreaBuilt: (v: number | '') => void;
  areaUseful: number | '';
  setAreaUseful: (v: number | '') => void;
  yearBuilt: number | '';
  setYearBuilt: (v: number | '') => void;
  rooms: number;
  setRooms: (v: number) => void;
  bathrooms: number;
  setBathrooms: (v: number) => void;
  condition: 'buen_estado' | 'a_reformar' | 'obra_nueva';
  setCondition: (v: 'buen_estado' | 'a_reformar' | 'obra_nueva') => void;
  energyCertificate: string;
  setEnergyCertificate: (v: string) => void;
  orientation: string;
  setOrientation: (v: string) => void;
  floorHeight: string;
  setFloorHeight: (v: string) => void;
  hasElevator: boolean;
  setHasElevator: (v: boolean) => void;
  hasParking: boolean;
  setHasParking: (v: boolean) => void;
  hasTerrace: boolean;
  setHasTerrace: (v: boolean) => void;
  hasPool: boolean;
  setHasPool: (v: boolean) => void;
  hasStorage: boolean;
  setHasStorage: (v: boolean) => void;
  hasHeating: boolean;
  setHasHeating: (v: boolean) => void;
  hasViews: boolean;
  setHasViews: (v: boolean) => void;
}

